//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//------------------------------------------------------------------------------

namespace SportShop.GUI.Owner
{


    public partial class Site1
    {

        /// <summary>
        /// head control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder head;

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// ScriptManager1 control.
        /// </summary>
        protected global::System.Web.UI.ScriptManager ScriptManager1;

        /// <summary>
        /// lnkProducts control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkProducts;

        /// <summary>
        /// lnkDashboard control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkDashboard;

        /// <summary>
        /// lnkOrders control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkOrders;

        /// <summary>
        /// lnkStore control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkStore;

        /// <summary>
        /// lnkReport control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkReport;

        /// <summary>
        /// lblUsername control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblUsername;

        /// <summary>
        /// btnLogout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnLogout;

        /// <summary>
        /// ContentPlaceHolder1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1;
    }
}